import { heightPercentageToDP as hp } from 'react-native-responsive-screen';

export const lightTheme = {
  colors: {
    primary: '#5E72E4',
    secondary: '#3EC1D3',
    accent: '#FF5678',
    background: '#FFFFFF',
    surface: '#F8F9FA',
    text: '#212121',
    subtext: '#757575',
    border: '#EEEEEE',
    notification: '#FF3B30',
    success: '#4CAF50',
    warning: '#FF9800',
    error: '#F44336',
    card: '#FFFFFF',
    disabled: '#BDBDBD',
    placeholder: '#9E9E9E',
    divider: '#EEEEEE',
    white: '#FFFFFF',
    black: '#000000',
    transparent: 'transparent',
  },
  spacing: {
    xs: hp(1),
    sm: hp(1.5),
    md: hp(2),
    lg: hp(3),
    xl: hp(4),
    xxl: hp(5),
  },
  typography: {
    h1: {
      fontSize: hp(3.5),
      fontWeight: 'bold',
      lineHeight: hp(4.5),
    },
    h2: {
      fontSize: hp(3),
      fontWeight: 'bold',
      lineHeight: hp(4),
    },
    h3: {
      fontSize: hp(2.5),
      fontWeight: '600',
      lineHeight: hp(3.5),
    },
    body: {
      fontSize: hp(2),
      fontWeight: 'normal',
      lineHeight: hp(3),
    },
    button: {
      fontSize: hp(2),
      fontWeight: '600',
      lineHeight: hp(3),
    },
    caption: {
      fontSize: hp(1.5),
      fontWeight: 'normal',
      lineHeight: hp(2),
    },
  },
  radius: {
    small: hp(1),
    medium: hp(1.5),
    large: hp(2.5),
    round: hp(5),
    circle: 9999,
  },
  shadows: {
    small: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.18,
      shadowRadius: 1.0,
      elevation: 1,
    },
    medium: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.20,
      shadowRadius: 1.41,
      elevation: 2,
    },
    large: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.22,
      shadowRadius: 2.22,
      elevation: 4,
    },
  },
};

export const darkTheme = {
  colors: {
    primary: '#7986CB',
    secondary: '#4DD0E1',
    accent: '#FF7597',
    background: '#121212',
    surface: '#1E1E1E',
    text: '#FFFFFF',
    subtext: '#B0B0B0',
    border: '#333333',
    notification: '#FF453A',
    success: '#66BB6A',
    warning: '#FFA726',
    error: '#EF5350',
    card: '#1E1E1E',
    disabled: '#5C5C5C',
    placeholder: '#757575',
    divider: '#2C2C2C',
    white: '#FFFFFF',
    black: '#000000',
    transparent: 'transparent',
  },
  spacing: lightTheme.spacing,
  typography: lightTheme.typography,
  radius: lightTheme.radius,
  shadows: lightTheme.shadows,
}; 